version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  build:
    commands:
      - echo "Running unit tests..."
      - python -m unittest test_circles.py
      - zip circles.zip circles.py
      
artifacts:
  files:
    - circles.zip
  base-directory: .